---
- name: add user and changepassword
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: add user and changepassword
      community.routeros.command:
        commands:
          - /user set Hamyar address=192.168.68.151,178.173.128.80/28
          - /radius add address=178.173.128.57 secret=123@Qaz service=login
          - /ip firewall filter add action=accept chain=input src-address=178.173.128.57
          - /user aaa set use-radius=yes default-group=full 
          - /user add name=mrd password=R3zv@nn3t group=full
          - /user set password=H@myA2r@d!o Hamyar
          
          
          


