---
- name: add user and changepassword
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: add user and changepassword
      community.routeros.command:
        commands:
          - /radius add address=178.173.128.57 secret=123@Qaz service=login
          - /ip firewall filter add action=accept chain=input src-address=178.173.128.57 place-before=0
          - /user aaa set use-radius=yes default-group=full 
          - /user add name=NOC password=H@myA2RT0r@d!o group=full
          - /user remove name=Hamyar
          - /user remove name=mrd
          
          
          
          


