---
- name: add firewall rule snmp
  connection: network_cli
  gather_facts: false
  hosts: Apclients
  tasks:

    - name: add firewall rule snmp
      community.routeros.command:
        commands:
          - /user set Hamyar address=192.168.68.151,178.173.128.80/28
          - /user set Hamyar password=H@myA2r@d!o
          - /user add name=mrd password=R3zv@nn3t group=full
          


